groups:
  - type: ufoShips
    categories:
      - type: Ufo
        tilesets:
          - type: UFO_110
            terrains:
              - U_EXT02
              - U_WALL02
              - U_BITS
          - type: UFO_120
            terrains:
              - U_EXT02
              - U_WALL02
              - U_BITS
          - type: UFO_130
            terrains:
              - U_EXT02
              - U_WALL02
              - U_DISEC2
              - U_BITS
          - type: UFO_140
            terrains:
              - U_EXT02
              - U_WALL02
              - U_OPER2
              - U_BITS
          - type: UFO_150
            terrains:
              - U_EXT02
              - U_WALL02
              - U_PODS
              - U_BITS
          - type: UFO_160
            terrains:
              - U_EXT02
              - U_WALL02
              - U_PODS
              - U_BITS
          - type: UFO_170
            terrains:
              - U_EXT02
              - U_WALL02
              - U_DISEC2
              - U_BITS
      - type: Craft
        tilesets:
          - type: AVENGER
            terrains:
              - AVENGER
          - type: LIGHTNIN
            terrains:
              - LIGHTNIN
          - type: PLANE
            terrains:
              - PLANE
  - type: ufoLandscapes
  - type: tftdShips
  - type: tftdLandscapes
