# This is the default MapConfig for MapViewII. It sets up the stock UFOs, Craft,
# and landscapes for out-of-the-box use by the app.
#
# 'tilesets' - a list that contains all the blocks.
# 'type'     - the label of MAP/RMP files for the block.
# 'terrains' - the label(s) of MCD/PCK/TAB files for the block.
# 'category' - a header for the tileset, is arbitrary here.
# 'group'    - a header for the categories, is arbitrary except that the first
#              letters designate the game-type and must be either 'ufo' or
#              'tftd' (case insensitive, with or without a following space).
# 'basepath' - the path to the parent directory of the tileset's files (default:
#              the resource directory(s) that was/were specified when MapView
#              was installed/configured). Note that Maps are expected to be in a
#              subdir called MAPS, Routes in a subdir called ROUTES, and
#              terrains - PCK/TAB/MCD files - in a subdir called TERRAIN.

tilesets:

# ---- UFOs -------------------------------------------------------------------#
  - type: UFO_110
    terrains:
      - U_EXT02
      - U_WALL02
      - U_BITS
    category: UFO
    group: ufoShips
  - type: UFO_120
    terrains:
      - U_EXT02
      - U_WALL02
      - U_BITS
    category: UFO
    group: ufoShips
  - type: UFO_130
    terrains:
      - U_EXT02
      - U_WALL02
      - U_DISEC2
      - U_BITS
    category: UFO
    group: ufoShips
  - type: UFO_140
    terrains:
      - U_EXT02
      - U_WALL02
      - U_OPER2
      - U_BITS
    category: UFO
    group: ufoShips
  - type: UFO_150
    terrains:
      - U_EXT02
      - U_WALL02
      - U_PODS
      - U_BITS
    category: UFO
    group: ufoShips
  - type: UFO_160
    terrains:
      - U_EXT02
      - U_WALL02
      - U_PODS
      - U_BITS
    category: UFO
    group: ufoShips
  - type: UFO_170
    terrains:
      - U_EXT02
      - U_WALL02
      - U_DISEC2
      - U_BITS
    category: UFO
    group: ufoShips

# ---- XCOM Craft -------------------------------------------------------------#
  - type: AVENGER
    terrains:
      - AVENGER
    category: Craft
    group: ufoShips
  - type: LIGHTNIN
    terrains:
      - LIGHTNIN
    category: Craft
    group: ufoShips
  - type: PLANE
    terrains:
      - PLANE
    category: Craft
    group: ufoShips

# ---- Landscapes -------------------------------------------------------------#
# ---- base xcom --------------------------------------------------------------#
  - type: XBASE_00
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_01
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_02
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_03
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_04
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_05
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_06
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_07
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_08
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_09
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_10
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_11
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_12
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_13
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_14
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_15
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_16
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_17
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_18
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_19
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes
  - type: XBASE_20
    terrains:
      - XBASE1
      - XBASE2
    category: base XCOM
    group: ufoLandscapes

# ---- base alien -------------------------------------------------------------#
  - type: UBASE_00
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_01
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_02
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_03
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_04
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_05
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_06
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_07
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_08
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_09
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_10
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_11
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_12
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_13
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_14
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes
  - type: UBASE_15
    terrains:
      - U_BASE
      - U_WALL02
      - U_PODS
      - BRAIN
    category: base aLien
    group: ufoLandscapes

# ---- cultivated -------------------------------------------------------------#
  - type: CULTA00
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA01
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA02
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA03
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA04
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA05
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA06
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA07
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA08
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA09
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA10
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA11
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA12
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA13
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA14
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA15
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA16
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA17
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes
  - type: CULTA18
    terrains:
      - CULTIVAT
      - BARN
    category: Cultivated
    group: ufoLandscapes

# ---- desert -----------------------------------------------------------------#
  - type: DESERT00
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT01
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT02
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT03
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT04
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT05
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT06
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT07
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT08
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT09
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT10
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes
  - type: DESERT11
    terrains:
      - DESERT
    category: Desert
    group: ufoLandscapes

# ---- forest -----------------------------------------------------------------#
  - type: FOREST00
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST01
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST02
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST03
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST04
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST05
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST06
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST07
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST08
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST09
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST10
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes
  - type: FOREST11
    terrains:
      - FOREST
    category: Forest
    group: ufoLandscapes

# ---- jungle -----------------------------------------------------------------#
  - type: JUNGLE00
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE01
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE02
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE03
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE04
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE05
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE06
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE07
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE08
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE09
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE10
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes
  - type: JUNGLE11
    terrains:
      - JUNGLE
    category: Jungle
    group: ufoLandscapes

# ---- mars -------------------------------------------------------------------#
  - type: MARS00
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS01
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS02
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS03
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS04
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS05
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS06
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS07
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS08
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS09
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes
  - type: MARS10
    terrains:
      - MARS
      - U_WALL02
    category: Mars
    group: ufoLandscapes

# ---- mountain ---------------------------------------------------------------#
  - type: MOUNT00
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT01
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT02
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT03
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT04
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT05
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT06
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT07
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT08
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT09
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT10
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT11
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes
  - type: MOUNT12
    terrains:
      - MOUNT
    category: Mountain
    group: ufoLandscapes

# ---- polar ------------------------------------------------------------------#
  - type: POLAR00
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR01
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR02
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR03
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR04
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR05
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR06
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR07
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR08
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR09
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR10
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR11
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR12
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes
  - type: POLAR13
    terrains:
      - POLAR
    category: Polar
    group: ufoLandscapes

# ---- urban ------------------------------------------------------------------#
  - type: URBAN00
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN01
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN02
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN03
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN04
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN05
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN06
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN07
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN08
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN09
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN14
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN15
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN16
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN17
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes
  - type: URBAN18
    terrains:
      - ROADS
      - URBITS
      - URBAN
      - FRNITURE
    category: Urban
    group: ufoLandscapes


#group: tftdShips
#group: tftdLandscapes
