# This is the default MapConfig for MapViewII. It sets up the stock UFOs, Craft,
# and landscapes for out-of-the-box use by the app.
#
# 'tilesets' - a list that contains all the blocks
# 'type'     - the label of MAP/RMP files for the block
# 'terrains' - the label(s) of MCD/PCK/TAB files for the block
# 'category' - a header for the tileset, is arbitrary here
# 'group'    - a header for the categories, is arbitrary here
tilesets:
  - type: UFO_110
    terrains:
      - U_EXT02
      - U_WALL02
      - U_BITS
    category: Ufo
    group: ufoShips
  - type: UFO_120
    terrains:
      - U_EXT02
      - U_WALL02
      - U_BITS
    category: Ufo
    group: ufoShips
  - type: UFO_130
    terrains:
      - U_EXT02
      - U_WALL02
      - U_DISEC2
      - U_BITS
    category: Ufo
    group: ufoShips
  - type: UFO_140
    terrains:
      - U_EXT02
      - U_WALL02
      - U_OPER2
      - U_BITS
    category: Ufo
    group: ufoShips
  - type: UFO_150
    terrains:
      - U_EXT02
      - U_WALL02
      - U_PODS
      - U_BITS
    category: Ufo
    group: ufoShips
  - type: UFO_160
    terrains:
      - U_EXT02
      - U_WALL02
      - U_PODS
      - U_BITS
    category: Ufo
    group: ufoShips
  - type: UFO_170
    terrains:
      - U_EXT02
      - U_WALL02
      - U_DISEC2
      - U_BITS
    category: Ufo
    group: ufoShips
  - type: AVENGER
    terrains:
      - AVENGER
    category: Craft
    group: ufoShips
  - type: LIGHTNIN
    terrains:
      - LIGHTNIN
    category: Craft
    group: ufoShips
  - type: PLANE
    terrains:
      - PLANE
    category: Craft
    group: ufoShips

#group: ufoLandscapes
#group: tftdShips
#group: tftdLandscapes
